import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE } from '@/lib/site';

export const metadata: Metadata = {
  title: { absolute: 'Service Contract | Cappadocia Airport Shuttle' },
  description: 'Service contract for Cappadocia Airport Shuttle shared shuttle and private airport transfer bookings.',
  alternates: { canonical:'/service-contract', languages:{ en:'/service-contract','zh-CN':'/zh-cn/service-contract','x-default':'/service-contract' } },
  robots: { index:false, follow:true },
  twitter: { card:'summary_large_image', title:'Service Contract | Cappadocia Airport Shuttle', description:'Terms that apply to Cappadocia Airport Shuttle reservations: payment, cancellation, hotel access, delays and liability.', images:['/cappadocia-airport-shuttle-vito-sprinter.webp'] },
};

export default function ServiceContractPage(){return <main>
  <section className="page-hero"><div className="container"><div className="breadcrumb"><Link href="/">Home</Link><span>›</span><span>Service Contract</span></div><span className="eyebrow">Booking terms</span><h1>Service Contract</h1><p className="lead">This contract explains the basic terms that apply when a Cappadocia Airport Shuttle reservation is confirmed.</p></div></section>
  <section className="section page-content-section"><div className="container privacy-prose prose">
    <section className="content-section"><h2>1. Parties</h2><p><strong>Website:</strong> {SITE.domain}</p><p><strong>Service Provider:</strong> {SITE.company}, TURSAB No: {SITE.tursab}. The passenger named in the reservation, together with other passengers included in the same booking, is referred to as the Customer.</p></section>
    <section className="content-section"><h2>2. Subject of the contract</h2><p>This contract covers shared airport shuttle and private airport transfer services reserved through Cappadocia Airport Shuttle between Kayseri Erkilet Airport (ASR), Nevsehir Kapadokya Airport (NAV) and supported Cappadocia accommodation areas.</p></section>
    <section className="content-section"><h2>3. When the contract applies</h2><p>The contract becomes effective when the Service Provider confirms the reservation. For a one-way booking it ends when that transfer is completed. For a round trip it ends after both confirmed journeys are completed, unless the booking is cancelled or changed beforehand.</p></section>
    <section className="content-section"><h2>4. Payment</h2><p>Standard payment is <strong>cash to the driver</strong>. Shared shuttle prices are per passenger; private transfer prices are per vehicle. The Customer is responsible for paying the price confirmed for the selected route and service.</p></section>
    <section className="content-section"><h2>5. Cancellation and changes</h2><p>If a reservation must be cancelled or changed, the Customer should inform the Service Provider as early as possible. Flight, airport, hotel, date, passenger count and contact changes should be sent before the transfer whenever possible.</p><p>Because the standard payment method is cash to the driver, a normal booking usually has no prepaid amount to refund. If an exceptional prepayment has been agreed, the cancellation conditions connected with that payment will be communicated separately.</p></section>
    <section className="content-section"><h2>6. Flight and pickup information</h2><p>The Customer must provide accurate flight and accommodation information. Airport arrival and hotel departure arrangements are coordinated from the confirmed booking details. Shared services can include other passengers travelling on compatible flights or hotel routes, so total journey time can vary from a direct private transfer.</p></section>
    <section className="content-section"><h2>7. Hotel access</h2><p>Some cave hotels, historic properties and village streets are narrow, steep or unsuitable for a larger vehicle to wait at the entrance. If direct access is not practical or safe, pickup or drop-off may use a nearby reachable point confirmed for the reservation.</p></section>
    <section className="content-section"><h2>8. Shared shuttle and private transfer</h2><p>A shared shuttle can carry passengers from separate reservations and may make additional hotel stops. A private transfer is reserved for the Customer's booking and uses the confirmed Vito or Sprinter category according to passenger and luggage requirements.</p></section>
    <section className="content-section"><h2>9. Passenger information</h2><p>The Customer is responsible for the accuracy of names, passport information where required for the reservation, flight details, hotel information and contact details submitted with the booking. The person making the reservation confirms that he or she is authorized to provide the necessary information for the passengers included in that booking.</p></section>
    <section className="content-section"><h2>10. Delays and circumstances outside reasonable control</h2><p>Traffic, road closures, weather, mechanical problems, airport restrictions, security measures, flight disruption and other events outside reasonable control can affect the service. When practical, the Service Provider will arrange a suitable alternative vehicle or an updated plan. If the Service Provider is completely unable to perform a paid service for a reason attributable to the Service Provider, any amount already paid for the unperformed service will be refunded.</p></section>
    <section className="content-section"><h2>11. Luggage and safety</h2><p>Unusually large luggage, sports equipment or other oversized items should be declared before the transfer so a suitable vehicle can be planned. Passengers must follow reasonable safety instructions from the driver and must not create a serious safety risk for other passengers, the driver or the vehicle.</p></section>
    <section className="content-section"><h2>12. Applicable law and acceptance</h2><p>This agreement is governed by applicable laws and regulations of the Republic of Turkiye. By submitting a reservation that is subsequently confirmed, the Customer states that the booking information is accurate and accepts this Service Contract on behalf of the passengers included in the reservation.</p><p>Questions about these terms can be sent through the <Link href="/contact-us">Contact Us</Link> page.</p></section>
  </div></section>
</main>}
