import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { JsonLd } from './JsonLd';
import { BookingInfoChecklist } from './BookingInfoChecklist';
import { LocalizedBookingForm } from './LocalizedBookingForm';
import { LocalizedContactForm } from './LocalizedContactForm';
import { MobileBookingCta } from './MobileBookingCta';
import { RichText } from './RichText';
import { WhatsAppIcon } from './WhatsAppIcon';
import { SITE, towns } from '@/lib/site';
import { localeOpenGraph, localePrefix, localeTownNames, localeUi, type NewLocale } from '@/lib/locale-config';
import { staticLocaleContent } from '@/lib/static-locale-content';
import { localeAlternates } from './LocalizedSeoPage';

const townKeys=Object.keys(towns) as (keyof typeof towns)[];
const homeLocaleText={
 es:{kayseri:'Aeropuerto de Kayseri',nevsehir:'Aeropuerto de Nevsehir',max:'máx.'},
 'pt-BR':{kayseri:'Aeroporto de Kayseri',nevsehir:'Aeroporto de Nevsehir',max:'máx.'},
 ko:{kayseri:'카이세리 공항',nevsehir:'네브셰히르 공항',max:'최대'},
 ja:{kayseri:'カイセリ空港',nevsehir:'ネヴシェヒル空港',max:'最大'},
} as const;
export type StaticPageKind='home'|'about'|'contact'|'privacy'|'contract';
export function localizedStaticMetadata(locale:NewLocale,kind:StaticPageKind):Metadata{
 const d=staticLocaleContent[locale],p=localePrefix[locale];
 const data=kind==='home'?d.home:kind==='about'?d.about:kind==='contact'?d.contact:kind==='privacy'?d.privacy:d.contract;
 const path=kind==='home'?'':kind==='about'?'/about-us':kind==='contact'?'/contact-us':kind==='privacy'?'/privacy-policy':'/service-contract';
 return {title:{absolute:data.title},description:data.description,alternates:{canonical:`${p}${path}`,languages:localeAlternates(path||'/')},robots:(kind==='privacy'||kind==='contract')?{index:false,follow:true}:{index:true,follow:true},openGraph:{type:'website',title:data.title,description:data.description,url:`${SITE.domain}${p}${path}`,locale:localeOpenGraph[locale],images:[{url:'/cappadocia-airport-shuttle-vito-sprinter.webp',width:1200,height:675,alt:'Cappadocia Airport Shuttle Mercedes Vito and Sprinter'}]},twitter:{card:'summary_large_image',title:data.title,description:data.description,images:['/cappadocia-airport-shuttle-vito-sprinter.webp']}};
}

export function LocalizedHomePage({locale}:{locale:NewLocale}){
 const d=staticLocaleContent[locale].home,p=localePrefix[locale],ui=localeUi[locale],names=localeTownNames[locale],lt=homeLocaleText[locale];
 const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:d.faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 const serviceSchema={'@context':'https://schema.org','@type':'Service',name:'Cappadocia Airport Shuttle',provider:{'@type':'TravelAgency',name:SITE.name,url:SITE.domain},areaServed:[{'@type':'Airport',name:'Kayseri Airport',iataCode:'ASR'},{'@type':'Airport',name:'Nevsehir Kapadokya Airport',alternateName:'Nevsehir Airport',iataCode:'NAV'},...townKeys.map(k=>({'@type':'Place',name:names[k]}))],serviceType:[ui.dynamic.shuttle,ui.form.privateTransfer],offers:[{'@type':'Offer',price:'15',priceCurrency:'EUR',description:`${d.labels.shared} · €15`},{'@type':'Offer',price:'90',priceCurrency:'EUR',description:`${lt.kayseri} · ${ui.form.privateTransfer} · Vito`},{'@type':'Offer',price:'110',priceCurrency:'EUR',description:`${lt.kayseri} · ${ui.form.privateTransfer} · Sprinter`},{'@type':'Offer',price:'80',priceCurrency:'EUR',description:`${lt.nevsehir} · ${ui.form.privateTransfer} · Vito`},{'@type':'Offer',price:'90',priceCurrency:'EUR',description:`${lt.nevsehir} · ${ui.form.privateTransfer} · Sprinter`}]};
 const guideSlugs=['cappadocia-airport','nearest-airport-to-cappadocia','cappadocia-shared-shuttle-vs-private-transfer','airport-transfer-prices','cappadocia-cave-hotel-airport-transfer','cappadocia-to-istanbul'];
 return <main className="has-booking-cta"><JsonLd data={serviceSchema}/><JsonLd data={faqSchema}/>
 <section className="home-hero"><div className="container hero-grid"><div className="hero-visual" aria-label="Cappadocia Airport Shuttle"><Image src="/cappadocia-airport-shuttle-vito-sprinter.webp" alt="Cappadocia Airport Shuttle Mercedes Vito and Sprinter" width={1200} height={675} priority sizes="(max-width: 800px) 94vw, 48vw"/></div><div className="hero-copy"><span className="eyebrow">{lt.kayseri} ASR · {lt.nevsehir} NAV</span><h1>Cappadocia Airport Shuttle</h1><p className="hero-price-highlight">{d.heroPrice}</p><p className="lead" dangerouslySetInnerHTML={{__html:d.lead}}/><div className="hero-actions"><a className="btn btn-primary" href="#booking">{d.book}</a><Link className="btn btn-secondary" href={`${p}/cappadocia-shared-shuttle-vs-private-transfer`}>{d.compare}</Link></div><div className="trust-row">{d.trust.map(x=><span key={x}>{x}</span>)}</div></div></div></section>
 <section className="section booking-section" id="booking"><div className="container home-booking-grid"><aside className="home-booking-info"><div className="kicker">{d.bookingKicker}</div><h2>{d.bookingHeading}</h2><div className="summary-box home-summary"><div className="summary-line"><span>{d.labels.shared}</span><strong>€15 / {d.labels.personWay}</strong></div><div className="summary-line"><span>{lt.kayseri} Vito · {lt.max} 5</span><strong>€90</strong></div><div className="summary-line"><span>{lt.kayseri} Sprinter · {lt.max} 16</span><strong>€110</strong></div><div className="summary-line"><span>{lt.nevsehir} Vito · {lt.max} 5</span><strong>€80</strong></div><div className="summary-line"><span>{lt.nevsehir} Sprinter · {lt.max} 16</span><strong>€90</strong></div></div><p className="small-copy">{d.bookingNote}</p><BookingInfoChecklist locale={locale} className="home-booking-checklist"/></aside><LocalizedBookingForm locale={locale}/></div></section>
 <section className="section section-muted"><div className="container"><div className="section-head"><div className="kicker">{d.whyKicker}</div><h2>{d.whyHeading}</h2><p>{d.whyLead}</p></div><div className="cards trust-cards">{d.trustCards.map(([h,x])=><div className="card" key={h}><h3>{h}</h3><p>{x}</p></div>)}</div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div className="kicker">{d.hubsKicker}</div><h2>{d.hubsHeading}</h2><p>{d.hubsLead}</p></div><div className="cards"><Link href={`${p}/kayseri-airport-shuttle`} className="card card-link"><h3>{d.hubCards[0][0]}</h3><p>{d.hubCards[0][1]}</p></Link><Link href={`${p}/nevsehir-airport-shuttle`} className="card card-link"><h3>{d.hubCards[1][0]}</h3><p>{d.hubCards[1][1]}</p></Link><Link href={`${p}/kayseri-or-nevsehir-airport-for-cappadocia`} className="card card-link"><h3>{d.hubCards[2][0]}</h3><p>{d.hubCards[2][1]}</p></Link></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div className="kicker">{d.arrivalKicker}</div><h2>{d.arrivalHeading}</h2><p>{d.arrivalLead}</p></div><div className="route-groups"><div><h3>{lt.kayseri} (ASR)</h3><div className="route-link-grid">{townKeys.map(k=><Link key={k} href={`${p}/kayseri-airport-to-${k}-shuttle`}><strong>{lt.kayseri} → {names[k]}</strong><span>{towns[k].distanceKayseri} · {towns[k].timeKayseri}</span><span>€15 {d.labels.shared} · {d.labels.cash}</span></Link>)}</div></div><div><h3>{lt.nevsehir} (NAV)</h3><div className="route-link-grid">{townKeys.map(k=><Link key={k} href={`${p}/nevsehir-airport-to-${k}-shuttle`}><strong>{lt.nevsehir} → {names[k]}</strong><span>{towns[k].distanceNevsehir} · {towns[k].timeNevsehir}</span><span>€15 {d.labels.shared} · {d.labels.cash}</span></Link>)}</div></div></div></div></section>
 <section className="section section-muted"><div className="container"><div className="section-head"><div className="kicker">{d.returnKicker}</div><h2>{d.returnHeading}</h2><p>{d.returnLead}</p></div><div className="route-groups"><div><h3>{d.labels.toKayseri}</h3><div className="route-link-grid">{townKeys.map(k=><Link key={k} href={`${p}/${k}-to-kayseri-airport-shuttle`}><strong>{names[k]} → {lt.kayseri}</strong><span>{towns[k].distanceKayseri} · {towns[k].timeKayseri}</span><span>€15 {d.labels.shared} · {d.labels.cash}</span></Link>)}</div></div><div><h3>{d.labels.toNevsehir}</h3><div className="route-link-grid">{townKeys.map(k=><Link key={k} href={`${p}/${k}-to-nevsehir-airport-shuttle`}><strong>{names[k]} → {lt.nevsehir}</strong><span>{towns[k].distanceNevsehir} · {towns[k].timeNevsehir}</span><span>€15 {d.labels.shared} · {d.labels.cash}</span></Link>)}</div></div></div></div></section>
 <section className="section"><div className="container content-grid homepage-content-grid"><article className="prose"><section className="content-section"><div className="kicker">{d.sharedKicker}</div><h2>{d.sharedHeading}</h2>{d.sharedParas.map((x,i)=><p key={i}><RichText text={x} prefix={p}/></p>)}</section><section className="content-section"><h2>{d.hotelHeading}</h2>{d.hotelParas.map((x,i)=><p key={i}><RichText text={x} prefix={p}/></p>)}</section><section className="content-section"><h2>{d.istanbulHeading}</h2><p><RichText text={d.istanbulPara} prefix={p}/></p></section></article><aside className="summary-box guide-box"><h3>{d.guidesHeading}</h3>{guideSlugs.map((s,i)=><Link key={s} href={`${p}/${s}`}>{d.guideLabels[i]}</Link>)}</aside></div></section>
 <section className="section section-muted"><div className="container"><div className="section-head"><div className="kicker">{d.faqKicker}</div><h2>{d.faqHeading}</h2></div><div className="faq faq-wide">{d.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><MobileBookingCta priceLabel={ui.dynamic.mobilePrice} bookLabel={ui.dynamic.bookNow} ariaLabel={ui.dynamic.quickBooking}/></main>;
}

export function LocalizedAboutPage({locale}:{locale:NewLocale}){const d=staticLocaleContent[locale].about,p=localePrefix[locale];const links=['kayseri-airport-shuttle','nevsehir-airport-shuttle','goreme-airport-transfer','private-airport-transfer-cappadocia','contact-us'];return <main><section className="page-hero"><div className="container"><div className="breadcrumb"><Link href={p}>{d.home}</Link><span>›</span><span>{d.crumb}</span></div><span className="eyebrow">{d.eyebrow}</span><h1>{d.h1}</h1><p className="lead">{d.lead}</p></div></section><section className="section page-content-section"><div className="container content-grid"><article className="prose">{d.sections.map(([h,ps])=><section className="content-section" key={h}><h2>{h}</h2>{ps.map((x,i)=><p key={i}>{x}</p>)}</section>)}</article><aside className="summary-box guide-box"><h3>{d.quick}</h3>{links.map((s,i)=><Link href={`${p}/${s}`} key={s}>{d.quickLinks[i]}</Link>)}</aside></div></section></main>}
export function LocalizedContactPage({locale}:{locale:NewLocale}){const d=staticLocaleContent[locale].contact,p=localePrefix[locale],m=encodeURIComponent(localeUi[locale].directWhatsapp);return <main><section className="page-hero"><div className="container"><div className="breadcrumb"><Link href={p}>{d.home}</Link><span>›</span><span>{d.crumb}</span></div><span className="eyebrow">{d.eyebrow}</span><h1>{d.h1}</h1><p className="lead">{d.lead}</p></div></section><section className="section page-content-section"><div className="container contact-grid"><div className="contact-card"><h2>{d.sendHeading}</h2><p>{d.sendIntro}</p><LocalizedContactForm locale={locale}/></div><aside className="contact-aside"><div className="summary-box"><h3>{d.direct}</h3><div className="contact-method"><span>WhatsApp</span><a href={`https://wa.me/${SITE.whatsappDigits}?text=${m}`} target="_blank" rel="noreferrer"><WhatsAppIcon size={18}/> {SITE.whatsappDisplay}</a></div></div><div className="summary-box"><h3>{d.before}</h3><p className="small-copy">{d.beforeText}</p></div><div className="summary-box"><h3>{d.agency}</h3><p className="small-copy">{SITE.company}<br/>TURSAB No: {SITE.tursab}</p><Link className="inline-link" href={`${p}/about-us`}>{d.about}</Link></div></aside></div></section></main>}
function LegalPage({locale,kind}:{locale:NewLocale;kind:'privacy'|'contract'}){const p=localePrefix[locale],d=kind==='privacy'?staticLocaleContent[locale].privacy:staticLocaleContent[locale].contract;return <main><section className="page-hero"><div className="container"><div className="breadcrumb"><Link href={p}>{d.home}</Link><span>›</span><span>{d.crumb}</span></div><span className="eyebrow">{d.eyebrow}</span><h1>{d.h1}</h1><p className="lead">{d.lead}</p></div></section><section className="section page-content-section"><div className="container privacy-prose prose">{d.sections.map(([h,ps])=><section className="content-section" key={h}><h2>{h}</h2>{ps.map((x,i)=><p key={i}>{x}</p>)}</section>)}<p><Link href={`${p}/contact-us`}>{d.contactLabel}</Link></p></div></section></main>}
export function LocalizedPrivacyPage({locale}:{locale:NewLocale}){return <LegalPage locale={locale} kind="privacy"/>}
export function LocalizedContractPage({locale}:{locale:NewLocale}){return <LegalPage locale={locale} kind="contract"/>}
export function LocalizedNotFoundPage({locale}:{locale:NewLocale}){const d=staticLocaleContent[locale].notFound,p=localePrefix[locale];return <main className="section"><div className="container"><h1>{d.h1}</h1><p className="lead">{d.lead}</p><Link className="btn btn-primary" href={p}>{d.back}</Link></div></main>}
