import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { BookingInfoChecklist } from '@/components/BookingInfoChecklist';
import { LocalizedBookingForm } from '@/components/LocalizedBookingForm';
import { QuickFacts } from '@/components/QuickFacts';
import { JsonLd } from '@/components/JsonLd';
import { MobileBookingCta } from '@/components/MobileBookingCta';
import { MeetingSteps } from '@/components/MeetingSteps';
import { RichText } from '@/components/RichText';
import { airports, SITE, towns } from '@/lib/site';
import { localeHtmlLang, localeOpenGraph, localePrefix, localeTownNames, localeUi, type NewLocale } from '@/lib/locale-config';
import { guideInlineBookingSectionCount, pageHasBookingForm, pageUsesGuideInlineBooking } from '@/lib/booking-visibility';

export type LocalizedSeoPageData = {
  slug:string; title:string; description:string; twitterTitle?:string; twitterDescription?:string;
  eyebrow:string; h1:string; lead:string;
  sections:{heading:string; paragraphs:string[]; bullets?:string[]}[];
  faq:{q:string;a:string}[]; related:string[];
  route?:{airport:'kayseri'|'nevsehir';town:keyof typeof towns;direction:'arrival'|'return'};
};

const WEBPAGE_GUIDE_SLUGS=new Set(['cappadocia-airport','nearest-airport-to-cappadocia','kayseri-or-nevsehir-airport-for-cappadocia','cappadocia-shared-shuttle-vs-private-transfer','istanbul-to-cappadocia','cappadocia-to-istanbul']);
const visibleAirportNames: Record<NewLocale,{kayseri:string;nevsehir:string}> = {
  es:{kayseri:'Kayseri',nevsehir:'Nevsehir'},
  'pt-BR':{kayseri:'Kayseri',nevsehir:'Nevsehir'},
  ko:{kayseri:'카이세리',nevsehir:'네브셰히르'},
  ja:{kayseri:'カイセリ',nevsehir:'ネヴシェヒル'},
};
const localeSeoText={
  es:{home:'Inicio',bookRoute:'Reservar este shuttle',bookService:'Reservar traslado',airportShuttle:'Shuttle aeropuerto',person:'persona',vehicle:'vehículo',sharedOffer:'Shuttle compartido por persona, solo ida',vitoOffer:'Mercedes Vito privado, solo ida, hasta 5 pasajeros',sprinterOffer:'Mercedes Sprinter privado, solo ida, hasta 16 pasajeros'},
  'pt-BR':{home:'Início',bookRoute:'Reservar este shuttle',bookService:'Reservar transfer',airportShuttle:'Shuttle aeroporto',person:'pessoa',vehicle:'veículo',sharedOffer:'Shuttle compartilhado por pessoa, somente ida',vitoOffer:'Mercedes Vito privativo, somente ida, até 5 passageiros',sprinterOffer:'Mercedes Sprinter privativo, somente ida, até 16 passageiros'},
  ko:{home:'홈',bookRoute:'이 셔틀 예약',bookService:'공항 픽업 예약',airportShuttle:'공항 셔틀',person:'인',vehicle:'차량',sharedOffer:'합승 셔틀 1인 편도',vitoOffer:'프라이빗 Mercedes Vito 편도, 최대 5명',sprinterOffer:'프라이빗 Mercedes Sprinter 편도, 최대 16명'},
  ja:{home:'ホーム',bookRoute:'このシャトルを予約',bookService:'空港送迎を予約',airportShuttle:'空港シャトル',person:'名',vehicle:'台',sharedOffer:'乗合シャトル 1名・片道',vitoOffer:'プライベートMercedes Vito・片道・最大5名',sprinterOffer:'プライベートMercedes Sprinter・片道・最大16名'},
} as const;

export function localeAlternates(path:string){
  const clean=path==='/'?'':path.startsWith('/')?path:`/${path}`;
  return {en:clean||'/', 'zh-CN':`/zh-cn${clean}`, es:`/es${clean}`, 'pt-BR':`/pt-br${clean}`, ko:`/ko${clean}`, ja:`/ja${clean}`, 'x-default':clean||'/'};
}
function airportSchema(airportKey:keyof typeof airports){const airport=airports[airportKey];return {'@type':'Airport',name:airportKey==='nevsehir'?airport.fullName:airport.name,alternateName:airportKey==='nevsehir'?airport.name:airport.fullName,iataCode:airport.code};}
function serviceAreaServed(page:LocalizedSeoPageData,locale:NewLocale){const names=localeTownNames[locale]; if(page.route)return [airportSchema(page.route.airport),{'@type':'Place',name:names[page.route.town]}]; const townPlaces=(Object.keys(towns) as (keyof typeof towns)[]).map(k=>({'@type':'Place',name:names[k]})); if(page.slug==='goreme-airport-transfer')return[airportSchema('kayseri'),airportSchema('nevsehir'),{'@type':'Place',name:names.goreme}]; if(page.slug.includes('kayseri')&&!page.slug.includes('nevsehir'))return[airportSchema('kayseri'),...townPlaces]; if(page.slug.includes('nevsehir')&&!page.slug.includes('kayseri'))return[airportSchema('nevsehir'),...townPlaces]; return[airportSchema('kayseri'),airportSchema('nevsehir'),...townPlaces];}
function plainRichText(text:string){return text.replace(/\[\[([^\]|]+)\|[^\]]+\]\]/g,'$1').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/\*([^*]+)\*/g,'$1');}
export function localizedMetadata(locale:NewLocale,page:LocalizedSeoPageData):Metadata{const p=localePrefix[locale];return{title:{absolute:page.title},description:page.description,alternates:{canonical:`${p}/${page.slug}`,languages:localeAlternates(`/${page.slug}`)},openGraph:{type:'website',title:page.title,description:page.description,url:`${SITE.domain}${p}/${page.slug}`,locale:localeOpenGraph[locale],images:[{url:'/cappadocia-airport-shuttle-vito-sprinter.webp',width:1200,height:675,alt:'Cappadocia Airport Shuttle Mercedes Vito and Sprinter'}]},twitter:{card:'summary_large_image',title:page.twitterTitle??page.title,description:page.twitterDescription??page.description,images:['/cappadocia-airport-shuttle-vito-sprinter.webp']}};}
function bookingDefaults(page:LocalizedSeoPageData){if(page.route)return{initialAirport:page.route.airport,initialDirection:page.route.direction==='arrival'?'airport-hotel' as const:'hotel-airport' as const,initialTown:String(page.route.town)}; const initialAirport=page.slug.includes('nevsehir')?'nevsehir' as const:'kayseri' as const; const townKey=(Object.keys(towns) as (keyof typeof towns)[]).find(k=>page.slug===`${String(k)}-airport-transfer`);return{initialAirport,initialDirection:page.slug.startsWith('cappadocia-to-')?'hotel-airport' as const:'airport-hotel' as const,initialTown:townKey?String(townKey):''};}
function AirportComparisonTables({locale}:{locale:NewLocale}){const t=localeUi[locale].dynamic,n=localeTownNames[locale],a=visibleAirportNames[locale];const rows=(Object.keys(towns) as (keyof typeof towns)[]).map(key=>({key,town:towns[key]}));return <section className="content-section airport-comparison-tables" aria-label={t.compareDistance}><h2>{t.compareDistance}</h2><div className="table-scroll"><table><thead><tr><th>{t.town}</th><th>{a.nevsehir} (NAV)</th><th>{a.kayseri} (ASR)</th></tr></thead><tbody>{rows.map(({key,town})=><tr key={key}><th scope="row">{n[key]}</th><td>{town.distanceNevsehir} / {town.timeNevsehir}</td><td>{town.distanceKayseri} / {town.timeKayseri}</td></tr>)}</tbody></table></div><h2>{t.comparePrices}</h2><div className="table-scroll"><table><thead><tr><th>{t.service}</th><th>{a.nevsehir} (NAV)</th><th>{a.kayseri} (ASR)</th></tr></thead><tbody><tr><th scope="row">{t.shared}</th><td>€15 / {t.person}</td><td>€15 / {t.person}</td></tr><tr><th scope="row">{t.privateVito}</th><td>€80 / {t.vehicle}</td><td>€90 / {t.vehicle}</td></tr><tr><th scope="row">{t.privateSprinter}</th><td>€90 / {t.vehicle}</td><td>€110 / {t.vehicle}</td></tr></tbody></table></div></section>}
function RouteSummary({locale,page}:{locale:NewLocale;page:LocalizedSeoPageData}){if(page.route)return null;const t=localeUi[locale].dynamic,a=visibleAirportNames[locale];return <div className="summary-box"><h3>{t.atGlance}</h3><div className="summary-line"><span>{t.shuttle}</span><strong>€15 / {t.person}</strong></div><div className="summary-line"><span>{a.kayseri} Vito</span><strong>€90 / {t.vehicle}</strong></div><div className="summary-line"><span>{a.kayseri} Sprinter</span><strong>€110 / {t.vehicle}</strong></div><div className="summary-line"><span>{a.nevsehir} Vito</span><strong>€80 / {t.vehicle}</strong></div><div className="summary-line"><span>{a.nevsehir} Sprinter</span><strong>€90 / {t.vehicle}</strong></div><div className="summary-line"><span>{t.payment}</span><strong>{t.cash}</strong></div></div>}
function RouteQuickFacts({locale,page}:{locale:NewLocale;page:LocalizedSeoPageData}){if(!page.route)return null;const t=towns[page.route.town],q=localeUi[locale].quick;return <QuickFacts ariaLabel={q.aria} items={[{label:q.distance,value:page.route.airport==='kayseri'?t.distanceKayseri:t.distanceNevsehir},{label:q.travelTime,value:page.route.airport==='kayseri'?t.timeKayseri:t.timeNevsehir},{label:q.price,value:`€15 / ${localeUi[locale].dynamic.person}`}]} />}
function RouteAirportMeeting({locale,page}:{locale:NewLocale;page:LocalizedSeoPageData}){if(!page.route||page.route.direction!=='arrival')return null;const t=localeUi[locale].dynamic;return <section className="content-section airport-meeting-section"><h2>{t.meetingHeading}</h2><p>{t.meetingText}</p><MeetingSteps ariaLabel={t.meetingAria} steps={t.meetingSteps.map(([title,description])=>({title,description}))}/></section>}

export function LocalizedSeoPage({locale,page,pretty}:{locale:NewLocale;page:LocalizedSeoPageData;pretty:(slug:string)=>string}){if(!page)notFound();const p=localePrefix[locale],t=localeUi[locale].dynamic,st=localeSeoText[locale];const faqSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:page.faq.map(i=>({'@type':'Question',name:i.q,acceptedAnswer:{'@type':'Answer',text:plainRichText(i.a)}}))};const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:st.home,item:`${SITE.domain}${p}`},{'@type':'ListItem',position:2,name:page.h1,item:`${SITE.domain}${p}/${page.slug}`}]};const primarySchema=WEBPAGE_GUIDE_SLUGS.has(page.slug)?{'@context':'https://schema.org','@type':'WebPage',name:page.h1,description:page.description,url:`${SITE.domain}${p}/${page.slug}`,inLanguage:localeHtmlLang[locale],isPartOf:{'@type':'WebSite',name:SITE.name,url:SITE.domain},publisher:{'@type':'TravelAgency',name:SITE.name,url:SITE.domain}}:{'@context':'https://schema.org','@type':'Service',name:page.h1,serviceType:page.h1,provider:{'@type':'TravelAgency',name:SITE.name,url:SITE.domain},areaServed:serviceAreaServed(page,locale),offers:page.route?[{'@type':'Offer',price:'15',priceCurrency:'EUR',description:st.sharedOffer},{'@type':'Offer',price:String(airports[page.route.airport].vito),priceCurrency:'EUR',description:st.vitoOffer},{'@type':'Offer',price:String(airports[page.route.airport].sprinter),priceCurrency:'EUR',description:st.sprinterOffer}]:undefined};const defaults=bookingDefaults(page);const hasBookingForm=pageHasBookingForm(page.slug,Boolean(page.route));const usesGuideInlineBooking=!page.route&&hasBookingForm&&pageUsesGuideInlineBooking(page.slug);const guideCount=usesGuideInlineBooking?guideInlineBookingSectionCount(page.slug):1;const mainClass=[page.route?'route-page':'',hasBookingForm?'has-booking-cta':''].filter(Boolean).join(' ')||undefined;
 const renderSections=(sections:typeof page.sections)=><>{sections.map(s=><section className="content-section" key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map((x,i)=><p key={i}><RichText text={x} prefix={p}/></p>)}{s.bullets&&<ul className={s.bullets.length>12?'long-list':undefined}>{s.bullets.map(b=><li key={b}><RichText text={b} prefix={p}/></li>)}</ul>}</section>)}</>;
 const related=<section className="content-section related-section"><h2>{t.related}</h2><div className="related-grid">{page.related.slice(0,8).map(r=><Link className="related-card" href={`${p}/${r}`} key={r}><strong>{pretty(r)}</strong><span>{t.relatedSub}</span></Link>)}</div></section>;
 const faq=<section className="content-section"><h2>{t.faq}</h2><div className="faq">{page.faq.map(i=><details key={i.q}><summary>{i.q}</summary><p><RichText text={i.a} prefix={p}/></p></details>)}</div></section>;
 return <main className={mainClass}><JsonLd data={faqSchema}/><JsonLd data={breadcrumb}/><JsonLd data={primarySchema}/><section className="page-hero"><div className="container"><div className="breadcrumb"><Link href={p}>{st.home}</Link><span>›</span><span>{page.h1}</span></div><span className="eyebrow">{page.eyebrow}</span><h1>{page.h1}</h1><p className="lead">{page.lead}</p><RouteQuickFacts locale={locale} page={page}/><div className="hero-actions"><a className="btn btn-primary" href={hasBookingForm?'#booking':`${p}/#booking`}>{page.route?st.bookRoute:st.bookService}</a><Link className="btn btn-secondary" href={p}>{st.airportShuttle}</Link></div><div className="trust-row"><span>WhatsApp</span><span>{localeUi[locale].form.oneWay} / {localeUi[locale].form.roundTrip}</span><span>{t.cash}</span></div></div></section><section className="section page-content-section"><div className={page.route?'container route-page-grid':hasBookingForm?`container content-grid${usesGuideInlineBooking?' guide-booking-grid':''}`:'container guide-content-wrap'}>{usesGuideInlineBooking?<><article className="prose guide-booking-intro">{page.slug==='kayseri-or-nevsehir-airport-for-cappadocia'&&<AirportComparisonTables locale={locale}/>} {renderSections(page.sections.slice(0,guideCount))}</article><aside className="sidebar guide-booking-sidebar" id="booking"><RouteSummary locale={locale} page={page}/><div className="sidebar-booking"><LocalizedBookingForm locale={locale} compact {...defaults}/></div></aside><article className="prose guide-booking-rest">{renderSections(page.sections.slice(guideCount))}<BookingInfoChecklist locale={locale}/>{related}{faq}</article></>:<><article className={page.route?'prose route-prose':'prose'}><RouteAirportMeeting locale={locale} page={page}/>{renderSections(page.sections)}{hasBookingForm&&<BookingInfoChecklist locale={locale}/>} {related}{faq}</article>{page.route&&<aside className="sidebar route-booking-sidebar" id="booking"><div className="sidebar-booking"><LocalizedBookingForm locale={locale} compact {...defaults}/></div></aside>}{!page.route&&hasBookingForm&&<aside className="sidebar" id="booking"><RouteSummary locale={locale} page={page}/><div className="sidebar-booking"><LocalizedBookingForm locale={locale} compact {...defaults}/></div></aside>}</>}</div></section>{hasBookingForm&&<MobileBookingCta priceLabel={t.mobilePrice} bookLabel={t.bookNow} ariaLabel={t.quickBooking}/>}</main>;
}
